blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/RSAf7b5njt
    about: We arent maintaining the extension anymore, but you can still join our Discord to chat with us.
  #- name: Issues
    #url: https://github.com/FastForwardTeam/FastForward/issues?q=label%3ANew-bypass
    #about: Please search before issues to check if a site is already submitted.
